### ISSUE TITLE
Can't locate native 'aiap-local-validator.node'

### ISSUE THREAD

**Issue by stephan-fischer** [OlehKulykov/aiap-local-validator#2]
Hi, i've installed the npm package in my electronjs app and i got this error:

> Uncaught Can't locate native 'aiap-local-validator.node' module in directories: build/Release,build/Debug,build,out/Release,out/Debug,Release,Debug,build/default,bin/winx64,bin/winx86

And this warning:

> client:135 ./node_modules/aiap-local-validator/index.js 21:25-91
Critical dependency: the request of a dependency is an expression

<img width="991" alt="Bildschirmfoto 2021-12-17 um 20 33 07" src="https://user-images.githubusercontent.com/2657649/146598273-620c281b-1c4e-4db6-b539-7315b6b9ba93.png">

My system:
MacOs 12.01

**Comment by OlehKulykov** [comment]
Greetings from Bayern,
this is a server side native package and requires compilation before using.

The exception means that the native/compiled module not found in a next dirs: https://github.com/OlehKulykov/aiap-local-validator/blob/master/index.js#L4 after successful compilation/installation.

So, please check next:
- You are using this module on server.
- You are using node version >= 10.0.0
- There are no compilation errors during/after installation `npm run install`.

**Comment by stephan-fischer** [comment]
Hi OlehKulykov, thanks!
Here is my environment:

npm -v 6.14.15
node -v 14.18.1

I don't have any compilation errors after npm install and i got this node file:
`node_modules/aiap-local-validator/build/Release/aiap-local-validator.node`

And i want to use the package in my electronjs MacOS application, to local validate receipts.
Debug Log Start:
`
NODE PATH /Users/xxx/node_modules/aiap-local-validator/build/Release/aiap-local-validator.node
NODE PATH /Users/xxx/node_modules/aiap-local-validator/build/Debug/aiap-local-validator.node
NODE PATH /Users/xxx/node_modules/aiap-local-validator/build/aiap-local-validator.node
NODE PATH /Users/xxx/node_modules/aiap-local-validator/out/Release/aiap-local-validator.node
NODE PATH /Users/xxx/node_modules/aiap-local-validator/out/Debug/aiap-local-validator.node
NODE PATH /Users/xxx/node_modules/aiap-local-validator/Release/aiap-local-validator.node
NODE PATH /Users/xxx/node_modules/aiap-local-validator/Debug/aiap-local-validator.node
NODE PATH /Users/xxx/node_modules/aiap-local-validator/build/default/aiap-local-validator.node
NODE PATH /Users/xxx/node_modules/aiap-local-validator/bin/winx64/aiap-local-validator.node
NODE PATH /Users/xxx/node_modules/aiap-local-validator/bin/winx86/aiap-local-validator.node
App threw an error during load
Can't locate native 'aiap-local-validator.node' module in directories: build/Release,build/Debug,build,out/Release,out/Debug,Release,Debug,build/default,bin/winx64,bin/winx8`

And part of verbose install:

npm install aiap-local-validator@latest -D --loglevel verbose  
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/xxx/Library/Caches/node-gyp/14.18.1
gyp verb `which` succeeded for `make` /usr/bin/make

**Comment by OlehKulykov** [comment]
Hi,
could you please send me the example of using, of course without the main functionality, to email: resdnt **at** gmail **dot** com
Or provide a link.

**Comment by stephan-fischer** [comment]
Hi OlehKulykov,

it is an electronjs issue, if you are using any electronjs starter package you can replicate this problem.
I have found a solution for it, you can use it directly, if you copy the node file into your project where the main.ts is:

`const { Validator, ErrorCode, InAppReceiptField } = require('./aiap-local-validator.node');`

And it works 😉 But i h've got this error:

`Error: The module '/Users/xxx/electron/aiap-local-validator.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 89. Please try re-compiling or re-installing`

Do you know if i can recompile it with the version 89? And works the code for sandbox receipts also?
Thank you very much!

**Comment by OlehKulykov** [comment]
Stephan,
unfortunately I do not know what electronjs doing, but true, there is an issue with versions.
Regarding the sandbox: yes, during the development I've used sandbox account and receipts from the app bundle.
